SPTGUI/urls.py
from django.conf.urls import url

from . import views, views_imports, views_tab_data, views_upload, views_email

app_name =  'SPTGUI'

urlpatterns = [
    ## Debug routes
    #url(r'^upload/tmp/$', views.upload_tmp, name='upload_tmp'),    ## TEMPORARY
    #url(r'^upload/$', views.upload_tmp_bknd, name='upload_tmp_bknd'),    ## TEMPORARY
    #url(r'^queue/status/$', views.queue_status, name='queue_status'),## TEMPORARY
    #url(r'^queue/new/$', views.queue_new, name='queue_new'),## TEMPORARY
    #url(r'^barchart/$', views.barchart, name='barchart'),## TEMPORARY
    #url(r'^popover/$', views.popover, name='popover'),## TEMPORARY

    ##
    ## ==== Email (these routes are duplicated in fastSPT/urls.py)
    ##
    url(r'^email/subscribe/$', views_email.email, name='email_subscribe'),
    url(r'^email/unsubscribe/(?P<token>.+)$',views_email.email_unsubscribe, name='email_unsubscribe'),
    url(r'^email/confirm/(?P<token>.+)$', views_email.email, name='email_confirm'),
    
    ##
    ## ==== Main routes
    ##
    url(r'^analysis/$', views.analysis_root, name='analysis_root'),
    url(r'^analysis/(?P<url_basename>.+)/upload/$', views_upload.upload, name='upload'),
    url(r'^analysis/(?P<url_basename>.+)/api/datasets/$', views_tab_data.datasets_api, name='datasets_api'),

    ##
    ## ==== Information about a dataset
    ##
url(r'^analysis/(?P<url_basename>.+)/datasets/(?P<dataset_id>[0-9]+)/original/$', views_imports.dataset_original, name='dataset_original'),
    url(r'^analysis/(?P<url_basename>.+)/datasets/(?P<dataset_id>[0-9]+)/parsed/$', views_imports.dataset_parsed, name='dataset_parsed'),
    url(r'^analysis/(?P<url_basename>.+)/datasets/(?P<dataset_id>[0-9]+)/report/$', views_imports.dataset_report, name='datasets_report'),


    ##
    ## ==== CRUD datasets
    ##
    url(r'^analysis/(?P<url_basename>.+)/api/delete/$', views_tab_data.delete_api, name='delete_api'),
    url(r'^analysis/(?P<url_basename>.+)/api/preprocessing/$', views_tab_data.preprocessing_api, name='preprocessing_api'),

    ##
    ## ==== Perform analysis
    ##
    url(r'^analysis/(?P<url_basename>.+)/api/analyze/$', views.analyze_api, name='analyze_api'),
    url(r'^analysis/(?P<url_basename>.+)/api/analyze/pooled$', views.get_analysisp, name='get_analysisp'),
    url(r'^analysis/(?P<url_basename>.+)/api/analyze/(?P<dataset_id>[0-9]+)$', views.get_analysis, name='get_analysis'),
    url(r'^analysis/(?P<url_basename>.+)/api/jld/pooled$', views.get_jldp, name='get_jldp'),
    url(r'^analysis/(?P<url_basename>.+)/api/jld_default/(?P<dataset_id>[0-9]+)$', views.get_jld_default, name='get_jld_default'),
    url(r'^analysis/(?P<url_basename>.+)/api/jld/$', views.get_jld, name='get_jld'),

    ##
    ## ==== TrackMate-SpotOn upload
    ##
    url('^uploadapi/$', views_upload.uploadapi, name='uploadapi'),

    ##
    ## ==== Default routes
    ##
    url(r'^analysis/new/', views.new_analysis, name='new_analysis'),
    url(r'^analysis/demo/', views.new_demo, name='new_demo'),
    url(r'^analysis/(?P<url_basename>.+)/debug', views.analysis_dbg, name='analysis_dbg'),
    url(r'^analysis/(?P<url_basename>.+)/', views.analysis, name='analysis'),
    url(r'^analysis/(?P<url_basename>.+)', views.analysis, name='analysis_noslash'),
    url(r'^$', views.index, name='index'),
    url(r'^contactform/', views_email.contactform, name='contactform'),
    url(r'^(?P<page>.+)', views.static, name='staticpage'),
]

fastSPT/urls.py
from SPTGUI import views, views_email
"""fastSPT URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^$', views.index),
    url(r'^SPTGUI/', include('SPTGUI.urls')),
    url(r'^admin/', admin.site.urls),
    ##
    ## ==== Email (these routes are duplicated in SPTGUI/urls.py)
    ##
    url(r'^email/subscribe/$', views_email.email, name='email_subscribe'),
    url(r'^email/unsubscribe/(?P<token>.+)$',views_email.email_unsubscribe, name='email_unsubscribe'),
    url(r'^email/confirm/(?P<token>.+)$', views_email.email, name='email_confirm'),
]

SPTGUI/views.py
# Index of views for the fastSPT-GUI app
# A graphical user interface to the fastSPT tool by Anders S. Hansen, 2016
# By MW, GPLv3+, Feb.-Apr. 2017

##
## ==== Imports
##
import random, string, json, os, hashlib, pickle, urlparse, logging, re, shutil
import fastspt

from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import Analysis, Dataset
from django.http import HttpResponse
from django.template import loader
from django.conf import settings
import fastSPT.custom_settings as custom_settings

from celery import celery
import tasks, config, recaptcha
import fitted_zcor, import_tools

# ==== Initialization
# careful a similar code exists in sockets_kinetics.py and sockets_tab_data.py
paths = {0: "./SPTGUI/fit_zcorr/0gaps",
         1: "./SPTGUI/fit_zcorr/1gaps",
         2: "./SPTGUI/fit_zcorr/2gaps"}
tree_init = fitted_zcor.init(paths=paths)

##
## ==== Global variables
##
hash_size = 16 ## Size of the prefix to save the fitted datasets
bf = "./static/analysis/" ## Location to save the fitted datasets


##
## === DBG VIEWS
##
if config.debug_views:
    logging.warning("'debug' is enabled")
    logging.warning("additional debug views have been loaded. Avoid that in production.")
    
    def barchart(request):
        """Returns a barchart template"""
        logging.warning("you called the `barchart` function, which is a 'debug' function, avoid that in production")
        template = loader.get_template('SPTGUI/barchart.html')
        context = {}
        return HttpResponse(template.render(context, request))

    def queue_status(request):
        """Returns the status of the queue"""
        logging.warning("you called the `queue_status` function, which is a 'debug' function, avoid that in production")        
        a = celery.app.control.inspect().reserved()['celery@alice']
        b = celery.app.control.inspect().active()['celery@alice']
        return HttpResponse(str(a)+str(b)+str(len(a))+" "+str(len(b)) )

    def popover(request):
        """Returns a simple popover, inspired from:
        http://plnkr.co/edit/ccb5MR?p=preview"""
        logging.warning("you called the `popover` function, which is a 'debug' function, avoid that in production")
        template = loader.get_template('SPTGUI/popover.html')
        context = {}
        return HttpResponse(template.render(context, request))            
    
##
## ==== Main views
##
def analysis_root(request):
    """A simple placeholder text for the root of the analysis/ route"""
    return HttpResponse("There's nothing here...")

def new_analysis(request):
    """The view that create a new analysis. This is the only way to create 
    a new analysis."""
    if request.method == "POST" or not custom_settings.RECAPTCHA_USE:
        ## Validate CAPTCHA
        if custom_settings.RECAPTCHA_USE:
            ip = recaptcha.get_client_ip(request)
            captcha_ok = recaptcha.grecaptcha_verify(request, custom_settings.RECAPTCHA_SECRET)

            if not captcha_ok['message']:
                return HttpResponse("Failed CAPTCHA, reason {}".format(captcha_ok['message']))
        
        ## Generate a name
        url_basename = import_tools.get_unused_namepage()
        
        ## Create the analysis if needed
        ana = Analysis(url_basename=url_basename,
                       pub_date=timezone.now(),
                       name='',
                       description='')
        ana.save()
        return redirect('SPTGUI:analysis', url_basename)
    else:
        return redirect('SPTGUI:index')

def new_demo(request):
    """Function that initiates a new demo analysis (with default datasets)"""
    if request.method == "POST" or not custom_settings.RECAPTCHA_USE:
        ## Validate CAPTCHA
        if custom_settings.RECAPTCHA_USE:
            ip = recaptcha.get_client_ip(request)
            captcha_ok = recaptcha.grecaptcha_verify(request, custom_settings.RECAPTCHA_SECRET)

            if not captcha_ok['message']:
                return HttpResponse("Failed CAPTCHA, reason {}".format(captcha_ok['message']))
        
        ## Generate a name
        url_basename = import_tools.get_unused_namepage()
        
        ## Duplicate the related datasets
        dem = list(Analysis.objects.filter(editable=False))[-1]
        url_basename_demo = dem.url_basename
        da = Dataset.objects.filter(analysis=dem)        
        print "The original analysis is {} and has {} datasets".format(dem.url_basename, len(da))
        
        ## Duplicate a demo analysis
        dem.id = None
        dem.pk = None
        dem.url_basename = url_basename
        dem.editable = True
        dem.pub_date=timezone.now()
        dem.save()
        
        ## Create the storage folder
        os.makedirs(os.path.join(bf,url_basename))
        cha = "03f9de26788d1c29" #'c0f7e565600c3bf5' # prefix for default jld
        
        for d in da: # Duplicate the related datasets. Does not duplicate the file
            #print "Duplicating {}".format(d)
            id_old = d.id
            d.pk = None
            d.id = None
            d.analysis = dem
            d.save()
            id_new = d.id
            path_old = os.path.join(bf, url_basename_demo,
                                    "jld_{}_{}.pkl".format(cha, id_old))
            path_new = os.path.join(bf, url_basename,
                                    "jld_{}_{}.pkl".format(cha, id_new))
            #print 'copy', path_old, path_new
            shutil.copyfile(path_old, path_new)

        print "New id: ", dem.id, " new name: ", url_basename
        return redirect('SPTGUI:analysis', url_basename)
    else:
        return redirect('../..')
    
    
def index(request):
    """Main view, returns the homepage template"""
    template = loader.get_template('SPTGUI/homepage.html')
    context = {'url_basename': 'new',
               'active': 'home',
               'captcha': custom_settings.RECAPTCHA_USE,
               'recaptchakey': custom_settings.RECAPTCHA_PUBLIC,
               'mailavailable': custom_settings.EMAIL_USE,
               'beta': custom_settings.BETA_VERSION,
               'demoavailable': custom_settings.use_demo}
    return HttpResponse(template.render(context, request))

def analysis(request, url_basename, run_tests=False):
    """Returns the analysis view. This is the main view of the system"""
    ana = get_object_or_404(Analysis, url_basename=url_basename)
    if not ana.editable:
        return HttpResponse('You cannot access this page') # Quick'n'dirty
    ana.acc_date = timezone.now()
    template = loader.get_template('SPTGUI/analysis.html')
    context = {'url_basename': url_basename,
               'active': 'analysis',
               'run_tests': run_tests,
               'lightlogo': True,
               'version': settings.APP_VERSION,
               'versionbackend': fastspt.__version__}
    ana.save()
    return HttpResponse(template.render(context, request))

def analysis_dbg(request, url_basename):
    if config.debug_views:
        print "Executing debug view"
        return analysis(request, url_basename, run_tests=True)

def static(request, page):
    """Returns a static page"""
    doc_versions = ['0.6', '0.7', '0.8', '0.9', '0.10', '0.11', '0.11.1']
    templates = {"docs": "documentation.html",
                 "about": "about.html",
                 "contact": "contact.html",
                 "license": "license.html",
                 "about": "about.html",
                 "privacy": "privacy.html"}
    context = {}
    templates_docs = {"docs/{}".format(k): "{}/{}".format(k, templates["docs"]) for k in doc_versions}
    for k in templates_docs:
        templates[k] = templates_docs[k]
    if config.debug_views:
        templates["docs_viz"] = "docs_viz.html"
    if page == 'docs':
        return redirect('SPTGUI:staticpage', 'docs/latest')
    elif page.startswith('docs/'):
        version = page.split('/')[1]
        context["versions"] = [{"version": i,
                                "url": "docs/{}".format(i)} for i in doc_versions]
        context["latest_version"] = False
        context["latest_version_number"] = str(doc_versions[-1])
        context["version_number"] = version
        
        if version not in [str(i) for i in doc_versions]: 
            version = 'latest'
        if version == 'latest' or version == str(doc_versions[-1]):
            page = "docs/{}".format(doc_versions[-1])
            context["latest_version"] = True
            context["version_number"] = str(doc_versions[-1])
            
    if page in templates:                
        template = loader.get_template('SPTGUI/{}'.format(templates[page]))
        context["active"] = page
        return HttpResponse(template.render(context, request))

## ==== Where are the views gone?
## view_import.py -> views providing statistics on the imported datasets
## views_tab_data.py -> Views involved in the display of the first tab (UploadController)

##
## ==== Other views
##


## ==== Analysis views
def analyze_api(request, url_basename):
    """This view, when called with a POST, starts the analysis (fitting of
    kinetic model) on a selection of datasets. When called with a GET, it 
    returns the progress of the analysis."""

    ana = get_object_or_404(Analysis, url_basename=url_basename)

    if request.method == 'GET': # return the '*_progress' object, if it exists
        cha = compute_hash2(request.GET['hashvalue'], request.GET['hashvalueJLD'])
        pa = bf+"{}/{}_progress.pkl".format(url_basename, cha)
        po = bf+"{}/{}_pooled.pkl".format(url_basename, cha)
        
        if os.path.exists(pa) :
            with open(pa, 'r') as f:
                save_pars = pickle.load(f)
            allgood = all([i['status']=='done' for i in save_pars['queue'].values()])
            return HttpResponse(json.dumps({'params': save_pars['pars'],
                                            'queue': save_pars['queue'],

SPTGUI/templates/SPTGUI/0.6/code.html
{% load static %}
<h2 class="blog-post-title">Code</h2>

<div class="col-md-8">
  <p>Spot-On is a free/open-source software, feel free to contribute by reporting bugs, helping us to write the documentation or proposing new features. The code of Spot-On is available on the software forge <a href="http://gitlab.com">GitLab</a>, in the <a href="https://gitlab.com/padouppadoup/Spot-On">Spot-On repository</a>. A <a href="https://gitlab.com/padouppadoup/Spot-On/issues">bugtracker</a> is also available for bug reports and feature requests.</p>
</div>

<div class="col-md-4">
  <img src="/static/SPTGUI/img/gitlab.png"
       class="img-responsive center-block"
       style="max-width: 80%;"
       alt="Gitlab logo">
</div>
<p> Spot-On is divided in several packages:

  <ul>
    <li>The web-interface</li>
    <li>The command-line backend, that can be used standalone and offline</li>
    <li>A Matlab© backend</li>
  </ul>
</p>
  
<p> The web-interface is released under the <a href="{% url 'SPTGUI:staticpage' 'license' %}">AGPL license</a>. The backend is released under the <a href="https://www.gnu.org/licenses/gpl.html">GNU GPL version 3+</a></p>

SPTGUI/templates/SPTGUI/0.6/docs_viz.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'SPTGUI/img/favicon.ico' %}">

    <title>Visualization test page</title>

    <!-- Spinner CSS -->
    <link href="{% static 'SPTGUI/dist/css/font-awesome-4.7.0/css/font-awesome.min.css' %}" rel="stylesheet">
    
    <!-- Bootstrap core CSS and JS -->
    <link href="{% static 'SPTGUI/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="{% static 'SPTGUI/dist/js/jquery.min.js' %}"></script>   
    <script src="{% static 'SPTGUI/dist/js/bootstrap.min.js' %}"></script>
    
    <!-- Angular JS -->
    <script src="{% static 'SPTGUI/dist/js/angular.js' %}"></script>
    <script src="{% static 'SPTGUI/dist/js/angular-toggle-switch.min.js' %}"></script>
    <script src="{% static 'SPTGUI/dist/js/ui-bootstrap-tpls-2.5.0.min.js' %}"></script>
    <link href="{% static 'SPTGUI/dist/css/angular-toggle-switch.css' %}" rel="stylesheet">

    <!-- Rzslider JS -->
    <link href="{% static 'SPTGUI/dist/css/rzslider.min.css' %}" rel="stylesheet">
    <script src="{% static 'SPTGUI/dist/js/rzslider.min.js' %}"></script>
    
    <!-- Custom app code & CSS -->
    <script src="{% static 'SPTGUI/docs_visualizations.js' %}"></script>

    <!-- D3.js -->
    <script src="{% static 'SPTGUI/dist/js/d3.v4.min.js' %}"></script>
      
  </head>
  
  <body ng-app="app">
    <div class="container">
      <h1> Applet for the jump length distribution</h1>
      <div ng-init="jld={D1: 1.0, D2: 5.0, P: 0.5, S: 10, dt: 10}">
	<jump-length-distribution data="jld"></jump-length-distribution>
	<br/>
	<table>
	  <tr>
	    <td class="col-sm-2">D<sub>1</sub> (&mu;m²/s)</td>
	    <td class="col-sm-10"><rzslider
		   rz-slider-model="jld.D1"
		   rz-slider-options="{floor: 0, ceil:10, step: 0.1, precision: 1}">
	    </rzslider></td>
	  </tr>
	  <tr>
	    <td class="col-sm-2">D<sub>2</sub> (&mu;m²/s)</td>
	    <td class="col-sm-10"><rzslider
		   rz-slider-model="jld.D2"
		   rz-slider-options="{floor: 0, ceil:10, step: 0.1, precision: 1}">
	    </rzslider></td>
	  </tr>
	  <tr>
	    <td class="col-sm-2">P</td>
	    <td class="col-sm-10"><rzslider
		   rz-slider-model="jld.P"
		   rz-slider-options="{floor: 0, ceil:1, step: 0.01, precision: 2}">
	    </rzslider></td>
	  </tr>
	  <tr>
	    <td class="col-sm-2">&sigma; (nm)</td>
	    <td class="col-sm-10"><rzslider
		   rz-slider-model="jld.S"
		   rz-slider-options="{floor: 0, ceil:100, step: 1}">
	    </rzslider></td>
	  </tr>
	  <tr>
	    <td class="col-sm-2">&Delta;t (ms)</td>
	    <td class="col-sm-10"><rzslider
		   rz-slider-model="jld.dt"
		   rz-slider-options="{floor: 1, ceil:100, step: 1}">
	    </rzslider></td>
	  </tr>
	</table>
      </div>
      <h1> Applet for the fraction lost in z</h1>
      <div class="alert alert-danger">WIP.</div>
      <fraction-lost></fraction-lost>
    </div>
  </body>
</html>

SPTGUI/templates/SPTGUI/0.6/faq.html
{% load static %}

<h2 class="blog-post-title">Frequently asked questions</h2>
<h3>What is Spot-On?</h3>
<p>Spot-On is an online tool to extract kinetic parameters from fast single particle tracking experiments. It does it in a manner that takes into account the finite depth of field of the objective and proposes corrections for that. Spot-On can fit two-states (Bound-Free) and three-states (Bound-Free1-Free2) models.</p>

<p>Spot-On takes a set of trajectories as input (<a href="#input-formats">multiple formats supported</a>) and outputs a fitted jump length distribution, together with goodness-of-fit metrics and the corresponding fitted coefficients.</p>
  

<h3>What is not Spot-On?</h3>
<p> Spot-On is not a tracking algorithm, thus you need to perform the tracking of your single particle tracking datasets using a separed algorithm. Spot-On accepts inputs from a range of <a href="#input-formats">popular tracking softwares</a>, and you can either add your own or write a converter towards a standard table-file import.</p>

<h3>What tracking software to use?</h3>

<h3>What type of input Spot-On accepts?</h3>

<p>See <a href="#input-formats">this section of the documentation</a>.</p>

<h3>My input format does not seem to be supported, what can I do?</h3>

<p>If the format of the tracking algorithm you use is not supported by Spot-On, here are a few things you can try:</p>

<ul>
  <li>If you believe that this format should be added to Spot-On, feel free to contact us, either through our <a href="{% url 'SPTGUI:contactform' %}">contact page</a> or by creating an issue on our <a href="https://gitlab.com/padouppadoup/Spot-On/">Gitlab bugtracker</a>.</li>
  <li>Meantime, you can try to convert your file to one of the formats supported by Spot-On. A description of the <a href="#input-formats">formats supported by Spot-On</a> is presented above. For instance, the CSV format has a very simple syntax.</li>
  <li> If you have programming skills, feel free to write an importer! The structure of the parser is documented in the <code>/SPTGUI/parsers.py</code> file. Do not forget to open an issue on the bugtracker so that we are aware that you are working on a specific file format.</li>
</ul>

<h3>How fast is Spot-On?</h3>
<p> During our tests that included up to 1 million detections, the computation of the jump length distribution and the fitting of the most complicated kinetic model (3 states with estimation of the localization error from the data) usually takes about one minute.</p>
<p> That said, the fitting speed depends on many parameters (load of the server, range of the parameters, shape of your jump length distribution, etc). If the online version of Spot-On is performing too slowly for your needs, feel free to get either the <a href="https://gitlab.com/padouppadoup/Spot-On/">offline version of Spot-On</a>, or the <a href="https://github.com/DarzacqLab/fastspt"> command line version</a>.</p>

<h3>Are you just fitting a two-exponential model?</h3>

<p> This is slightly more complicated, for several reasons presented in details in the <a href="methods">methods section</a>:</p>

<ul>
  <li>Spot-On can perform both two- and three-populations fitting</li>
  <li>Spot-On can estimate the localization error from the data</li>
  <li>As fast populations tend to move out of focus more than bound molecules, the estimate of the fraction of the molecules in each state is usually heavily biased towards slow-moving particles. Spot-On implements a previously-published semi-empirical correction to account for that.</li>
  <li> Spot-On implements quality checks to warn the user when the uploaded datasets seem to show inconsistencies or were performed in conditions that might lead to unreliable parameter estimation.</li>
</ul>

<h3>I'm afraid of uploading my dataset to your server. Is there an offline version?</h3>

<p> Sure! Spot-On is fully <a href="{% url 'SPTGUI:staticpage' 'license' %}">free/open-source</a> and detailed download and installation instructions can be retrieved from our <a href="https://gitlab.com/padouppadoup/Spot-On/">Gitlab page</a>.</p>

<h3>Is there a command-line version?</h3>
<p> There is! Spot-On uses an independent command-line Python backend that is available in our <a href="https://github.com/DarzacqLab/fastspt">Github repository</a>. It implements most of the features of Spot-On, comes with simple wrapper functions that can quickly be implemented in your scripting framework.</p>

<h3>What technology uses Spot-On?</h3>
<p> Spot-On is written in <a href="http://python.org">Python</a>. The backend relies on the <a href="https://lmfit.github.io/lmfit-py/">lmfit</a> library. The server is based on <a href="https://www.djangoproject.com/">Django</a> and uses <a href="http://celeryproject.org/">Celery</a> to run an asynchronous queue to perform jobs. The frontend is written in <a href="https://angularjs.org/">AngularJS</a> and the graphs are rendered through <a href="http://d3js.org/">D3.js</a>.</p>
  
<h3>Is there a Matlab® version?</h3>
<p>There is! Check this page (to be updated soon, <a href="{% url 'SPTGUI:contactform' %}">contact us</a> to get the version as soon as we release it).</p>

<h3>What license uses Spot-On?</h3>
<p>Spot-On is two-folds: </p>

<ul>
  <li><em>The <a href="https://github.com/DarzacqLab/fastspt">fitting backend</a></em> is released under the <a href="https://www.gnu.org/licenses/gpl-3.0.html">GNU General Public License version 3 or higher</a>. You can consult one of these links for a summary of the license: [<a href="https://tldrlegal.com/license/gnu-general-public-license-v3-%28gpl-3%29">1</a>] [<a href="https://choosealicense.com/licenses/gpl-3.0/">2</a>].</li>
  
  <li><em>The <a href="https://gitlab.com/padouppadoup/Spot-On/">server frontend</a></em>, that wraps the fitting backend is released under the <a href="https://www.gnu.org/licenses/agpl-3.0.html">GNU Affero General Public License version 3 or higher</a>. You can consult one of these links for a summary of the license: [<a href="https://tldrlegal.com/license/gnu-affero-general-public-license-v3-%28agpl-3.0%29">1</a>] [<a href="https://choosealicense.com/licenses/agpl-3.0/">2</a>].</li>
  
</ul>
<div class="row">
  <div class="col-md-6">
    <img src="{% static '/SPTGUI/img/icons/agplv3.png' %}"
	 class="img-responsive center-block"
	 style="max-width: 80%;"
	 alt="AGPLv3 logo">
  </div>
  <div class="col-md-6">
    <img src="{% static '/SPTGUI/img/icons/gplv3.png' %}"
	 class="img-responsive center-block"
	 style="max-width: 80%;"
	 alt="GPLv3 logo">
  </div>
</div>
<h3>I have a question</h3>

<p> We'd love to hear it! You can either:</p>

<ul>
  <li>Contact us by email (using our <a href="{% url 'SPTGUI:contactform' %}">contact form</a>)</li>
  <li>Open an issue on our <a href="https://gitlab.com/padouppadoup/Spot-On/issues">Gitlab bugtracker</a></li>
</ul>

<h3>How do you handle privacy?</h3>

<p>We only collect minimal information when you upload your datasets (your IP is saved somwhere in the logs but we don't use it), we do not ask for email or identification: no account is required to use Spot-On. Furthermore, you can erase your analysis anytime by going to the <em>Settings</em> tab in the analysis page. Finally, we provide an offline and a command-line version that you can run on your own machine. If you have any concern, feel free to <a href="{% url 'SPTGUI:contactform' %}">write to us.</a></p>

<h3>How to cite Spot-On?</h3>

<p>We've no idea so far!</p>

<h3>How to contact you?</h3>

<p>We have a <a href="{% url 'SPTGUI:contactform' %}">contact form</a>. You will receive a copy of your message and we will then communicate by email.</p>

<h3>I found a bug, how can I report it?</h3>  

<p>Thanks a lot for letting us know, this is really important to us! You can either open an issue on our <a href="https://gitlab.com/padouppadoup/Spot-On/issues">Gitlab bugtracker</a> or <a href="{% url 'SPTGUI:contactform' %}">drop us a message</a>.</p>